# An?lise Missing

library(Hmisc)
library(ggplot2)
library(VIM)

# Le arquivo csv exportado do MySQL
sus <- read.csv("c:/sus/sus5000rand.csv",header=T)
sus <- read.csv("/Users/rpietro/Google Drive/R/nonpublicdata_publications/SUS/sus5000rand.csv",header=T)

#label(hpv$IDADE) <- "age at the time of the first consultation"

# label SUS
label(sus$UF_ZI) <- "Munic?pio Gestor"
label(sus$ANO_CMPT) <- "Ano Compet?ncia" 
label(sus$MES_CMPT) <- "M?s Compet?ncia"
label(sus$ESPEC) <- "Especialidade"
label(sus$CGC_HOSP) <- "CGC Hospital"
label(sus$N_AIH) <- "N?mero do AIH"
label(sus$IDENT) <- "Identifica??o do tipo de AIH"
label(sus$CEP) <- "CEP do Paciente"
label(sus$MUNIC_RES) <- "Munic?pio do Paciente"
label(sus$NASC) <- "Data Nascimento do Paciente"
label(sus$SEXO) <- "Sexo do Paciente"
label(sus$UTI_MES_IN) <- "Dias de UTI no m?s inicial da interna??o"
label(sus$UTI_MES_AN) <- "Dias de UTI no m?s anterior a alta"
label(sus$UTI_MES_AL) <- "Dias de UTI no m?s da alta"
label(sus$UTI_MES_TO) <- "Quantidade de atod-UTI"
label(sus$MARCA_UTI) <- "Marca de UTI-Depende do ato"
label(sus$UTI_INT_IN) <- "Dias em UTI no m?s inicial - ato 34 ou 56"
label(sus$UTI_INT_AN) <- "Dias em UTI no m?s anterior a alta - ato 34 ou 56"
label(sus$UTI_INT_AL) <- "Dias em UTI no m?s da alta - ato 34 ou 56"
label(sus$UTI_INT_TO) <- "Totaliza dias em UTI - ato 34 ou 56"
label(sus$DIAR_ACOM) <- "Qtde de di?rias de acompanhante"
label(sus$PROC_SOLIC) <- "C?digo de procedimento solicitado"
label(sus$PROC_REA) <- "C?digo de procedimento realizado"
label(sus$VAL_SH) <- "Valor dos servi?os hospitalares"
label(sus$VAL_SP) <- "Valor dos sercvi?os prestados por terceiros"
label(sus$VAL_SADT) <- "Valor de SADT"
label(sus$VAL_RN) <- "Valor de recem-nato"
label(sus$VAL_ACOMP) <- "Valor de acompanhante"
label(sus$VAL_ORTP) <- "Valor de ?rtese e pr?tese"
label(sus$VAL_SANGUE) <- "Valor de sangue"
label(sus$VAL_SADTSR) <- "Valor de SADT sem rateio"
label(sus$VAL_TRANSP) <- "Valor de transplante"
label(sus$VAL_OBSANG) <- "Valor de anestesia"
label(sus$VAL_PED1AC) <- "Valor de pediatria"
label(sus$VAL_TOT) <- "Valor total"
label(sus$VAL_UTI) <- "Valor de UTI"
label(sus$US_TOT) <- "Valor total em dolar"
label(sus$DT_INTER) <- "Data interna??o"
label(sus$DT_SAIDA) <- "Data sa?da"
label(sus$DIAG_PRINC) <- "Diagn?sitco principal"
label(sus$DIAG_SECUN) <- "Diagn?stico secund?rio"
label(sus$COBRANCA) <- "Motivo de cobran?a"
label(sus$NATUREZA) <- "Natureza jur?dica do hospital"
label(sus$GESTAO) <- "?rg?o emissor do gestor"
label(sus$RUBRICA) <- "N?mero da rubrica"
label(sus$IND_VDRL) <- "Exame VDRL"
label(sus$MUNIC_MOV) <- "Munic?pio do hospital"
label(sus$COD_IDADE) <- "C?digo da Idade"
label(sus$IDADE) <- "Idade"
label(sus$DIAS_PERM) <- "Dias de perma?ncia"
label(sus$MORTE) <- "?bito"
label(sus$NACIONAL) <- "Nacionalidade"
label(sus$NUM_PROC) <- "N?mero do processamento"
label(sus$CAR_INT) <- "Carater de interna??o"
label(sus$TOT_PT_SP) <- "Total de pontos em SP"
label(sus$CPF_AUT) <- "CPF do auditor que autorizou o homonimo"
label(sus$HOMONIMO) <- "Marca de homonimo"
label(sus$NUM_FILHOS) <- "Qtde de filhos do paciente"
label(sus$INSTRU) <- "Grau de instru??o"
label(sus$CID_NOTIF) <- "Cid de notifica??o"
label(sus$CONTRACEP1) <- "M?todo contraceptivo1"
label(sus$CONTRACEP2) <- "M?todo contraceptivo2"
label(sus$GESTRISCO) <- "Gestante de alto risco"
label(sus$INSC_PN) <- "N?mero da gestante no pre-natal"
label(sus$SEQ_AIH5) <- "Sequencial da AIH tipo 5 - Longa perman?ncia"
label(sus$CBOR) <- "C?digo CBO"
label(sus$CNAER) <- "C?digo de acidente de trabalho"
label(sus$VINCPREV) <- "V?nculo com a previd?ncia"
label(sus$GESTOR_COD) <- "C?digo da autoriza??o pagamento"
label(sus$GESTOR_TP) <- "Tipo de Gesstor???"
label(sus$GESTOR_CPF) <- "CPF do Gestor"
label(sus$GESTOR_DT) <- "Gestor_DT???"
label(sus$CNES) <- "C?digo do CNES"
label(sus$CNPJ_MANT) <- "CNPJ_MANT???"
label(sus$INFEHOSP) <- "INFEHOSP???"
label(sus$CID_ASSO) <- "CID Causa"
label(sus$CID_MORTE) <- "CID Morte"
label(sus$COMPLEX) <- "COMPLEX???"
label(sus$FINANC) <- "FINANC???"
label(sus$FAEC_TP) <- "FAEC_TP???"
label(sus$REGCT) <- "REGCT???"
label(sus$RACA_COR) <- "RACA_COR???"
label(sus$ETNIA) <- "ETNIA???"
label(sus$ARQUIVO) <- "ARQUIVO???"

## Introduction
describe(sus, exclude.missing=FALSE)
View(sus)

